{
  description = "riso - modular ricing framework";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    let
      # Shared by the overlay and by packages.default, so a consumer that
      # applies the overlay gets exactly what this flake builds.
      risoPackage = pkgs:
        pkgs.rustPlatform.buildRustPackage {
          pname = "riso";
          version = "0.1.0";
          src = ./.;
          cargoLock.lockFile = ./Cargo.lock;

          nativeBuildInputs = [ pkgs.installShellFiles ];
          postInstall = ''
            installManPage docs/riso.1
            install -Dm644 NOTICE $out/share/doc/riso/NOTICE
          '';
          meta = {
            description = "Modular ricing framework";
            homepage = "https://github.com/eldios/riso";
            mainProgram = "riso";
            license = pkgs.lib.licenses.mit;
            platforms = pkgs.lib.platforms.unix;
          };
        };
    in
    {
      overlays.default = final: _prev: {
        riso = risoPackage final;
      };
    }
    // flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        packages.default = risoPackage pkgs;
        packages.riso = risoPackage pkgs;

        devShells.default = pkgs.mkShell {
          packages = with pkgs; [
            # toolchain
            cargo
            rustc
            rust-analyzer

            # CI gates
            rustfmt
            clippy

            # the conformance fixtures are regenerated by running the upstream
            # shell pipeline, which is bash and awk
            bash
            gawk
            git

            # task runner
            just
          ];

          RUST_BACKTRACE = "1";
        };
      });
}
