{
  description = "riso - modular ricing framework";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    let
      # Shared by the overlay, packages.default and the nixpkgs submission:
      # one derivation, defined once. See packaging/package.nix.
      risoPackage = pkgs: pkgs.callPackage ./packaging/package.nix { };
    in
    {
      overlays.default = final: _prev: {
        riso = risoPackage final;
      };
    }
    // flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        packages.default = risoPackage pkgs;
        packages.riso = risoPackage pkgs;

        devShells.default = pkgs.mkShell {
          packages = with pkgs; [
            # toolchain
            cargo
            rustc
            rust-analyzer

            # CI gates
            rustfmt
            clippy

            # the conformance fixtures are regenerated by running the upstream
            # shell pipeline, which is bash and awk
            bash
            gawk
            git

            # task runner
            just

            # dry-run the GitHub workflow locally (needs docker at run time)
            act
          ];

          RUST_BACKTRACE = "1";
        };
      });
}
