# Generated by riso. Edits are lost on the next theme change.
theme[main_bg]="{{ background }}"
theme[main_fg]="{{ foreground }}"
theme[title]="{{ bright_foreground }}"
theme[hi_fg]="{{ accent }}"
theme[selected_bg]="{{ selection_background }}"
theme[selected_fg]="{{ selection_foreground }}"
theme[inactive_fg]="{{ muted }}"
theme[graph_text]="{{ foreground }}"
theme[meter_bg]="{{ lighter_background }}"
theme[proc_misc]="{{ accent }}"

theme[cpu_box]="{{ muted }}"
theme[mem_box]="{{ muted }}"
theme[net_box]="{{ muted }}"
theme[proc_box]="{{ muted }}"
theme[div_line]="{{ muted }}"

theme[temp_start]="{{ green }}"
theme[temp_mid]="{{ yellow }}"
theme[temp_end]="{{ red }}"

theme[cpu_start]="{{ green }}"
theme[cpu_mid]="{{ yellow }}"
theme[cpu_end]="{{ red }}"

theme[free_start]="{{ green }}"
theme[free_mid]="{{ cyan }}"
theme[free_end]="{{ blue }}"

theme[cached_start]="{{ cyan }}"
theme[cached_mid]="{{ blue }}"
theme[cached_end]="{{ magenta }}"

theme[available_start]="{{ yellow }}"
theme[available_mid]="{{ orange }}"
theme[available_end]="{{ red }}"

theme[used_start]="{{ green }}"
theme[used_mid]="{{ yellow }}"
theme[used_end]="{{ red }}"

theme[download_start]="{{ cyan }}"
theme[download_mid]="{{ blue }}"
theme[download_end]="{{ magenta }}"

theme[upload_start]="{{ yellow }}"
theme[upload_mid]="{{ orange }}"
theme[upload_end]="{{ red }}"
