{
  "name": "riso",
  "flavour": "riso",
  "mode": "{{ mode }}",
  "colours": {
    "primary": "{{ accent_strip }}",
    "onPrimary": "{{ background_strip }}",
    "primaryContainer": "{{ selection_strip }}",
    "onPrimaryContainer": "{{ bright_foreground_strip }}",
    "primaryFixed": "{{ accent_strip }}",
    "primaryFixedDim": "{{ mix_strip accent background 25% }}",
    "onPrimaryFixed": "{{ background_strip }}",
    "onPrimaryFixedVariant": "{{ dark_background_strip }}",
    "inversePrimary": "{{ mix_strip accent foreground 40% }}",
    "secondary": "{{ magenta_strip }}",
    "onSecondary": "{{ background_strip }}",
    "secondaryContainer": "{{ mix_strip magenta background 70% }}",
    "onSecondaryContainer": "{{ bright_foreground_strip }}",
    "secondaryFixed": "{{ magenta_strip }}",
    "secondaryFixedDim": "{{ mix_strip magenta background 25% }}",
    "onSecondaryFixed": "{{ background_strip }}",
    "onSecondaryFixedVariant": "{{ dark_background_strip }}",
    "tertiary": "{{ cyan_strip }}",
    "onTertiary": "{{ background_strip }}",
    "tertiaryContainer": "{{ mix_strip cyan background 70% }}",
    "onTertiaryContainer": "{{ bright_foreground_strip }}",
    "tertiaryFixed": "{{ cyan_strip }}",
    "tertiaryFixedDim": "{{ mix_strip cyan background 25% }}",
    "onTertiaryFixed": "{{ background_strip }}",
    "onTertiaryFixedVariant": "{{ dark_background_strip }}",
    "background": "{{ background_strip }}",
    "onBackground": "{{ foreground_strip }}",
    "surface": "{{ background_strip }}",
    "onSurface": "{{ foreground_strip }}",
    "surfaceVariant": "{{ lighter_background_strip }}",
    "onSurfaceVariant": "{{ light_foreground_strip }}",
    "surfaceDim": "{{ dark_background_strip }}",
    "surfaceBright": "{{ mix_strip background foreground 12% }}",
    "surfaceContainerLowest": "{{ darker_background_strip }}",
    "surfaceContainerLow": "{{ dark_background_strip }}",
    "surfaceContainer": "{{ mix_strip background foreground 6% }}",
    "surfaceContainerHigh": "{{ mix_strip background foreground 11% }}",
    "surfaceContainerHighest": "{{ mix_strip background foreground 16% }}",
    "surfaceTint": "{{ accent_strip }}",
    "inverseSurface": "{{ foreground_strip }}",
    "inverseOnSurface": "{{ background_strip }}",
    "outline": "{{ muted_strip }}",
    "outlineVariant": "{{ mix_strip muted background 50% }}",
    "shadow": "000000",
    "scrim": "000000",
    "neutral": "{{ muted_strip }}",
    "error": "{{ red_strip }}",
    "onError": "{{ background_strip }}",
    "errorContainer": "{{ mix_strip red background 70% }}",
    "onErrorContainer": "{{ bright_foreground_strip }}",
    "success": "{{ green_strip }}",
    "onSuccess": "{{ background_strip }}",
    "successContainer": "{{ mix_strip green background 70% }}",
    "onSuccessContainer": "{{ bright_foreground_strip }}",
    "term0": "{{ color0_strip }}",
    "term1": "{{ color1_strip }}",
    "term2": "{{ color2_strip }}",
    "term3": "{{ color3_strip }}",
    "term4": "{{ color4_strip }}",
    "term5": "{{ color5_strip }}",
    "term6": "{{ color6_strip }}",
    "term7": "{{ color7_strip }}",
    "term8": "{{ color8_strip }}",
    "term9": "{{ color9_strip }}",
    "term10": "{{ color10_strip }}",
    "term11": "{{ color11_strip }}",
    "term12": "{{ color12_strip }}",
    "term13": "{{ color13_strip }}",
    "term14": "{{ color14_strip }}",
    "term15": "{{ color15_strip }}"
  }
}
