# Generated by riso. Edits are lost on the next theme change.
"ui.background" = { bg = "background" }
"ui.text" = { fg = "foreground" }
"ui.text.focus" = { fg = "bright_foreground" }
"ui.cursor" = { fg = "background", bg = "bright_foreground" }
"ui.cursor.primary" = { fg = "background", bg = "accent" }
"ui.cursorline.primary" = { bg = "lighter_background" }
"ui.selection" = { bg = "selection" }
"ui.linenr" = { fg = "muted" }
"ui.linenr.selected" = { fg = "foreground" }
"ui.statusline" = { fg = "foreground", bg = "lighter_background" }
"ui.statusline.inactive" = { fg = "muted", bg = "dark_background" }
"ui.popup" = { fg = "foreground", bg = "lighter_background" }
"ui.menu" = { fg = "foreground", bg = "lighter_background" }
"ui.menu.selected" = { fg = "background", bg = "accent" }
"ui.virtual.whitespace" = { fg = "muted" }
"ui.virtual.ruler" = { bg = "lighter_background" }
"ui.help" = { fg = "foreground", bg = "lighter_background" }

"comment" = { fg = "muted", modifiers = ["italic"] }
"variable" = { fg = "foreground" }
"constant" = { fg = "orange" }
"constant.numeric" = { fg = "orange" }
"string" = { fg = "green" }
"keyword" = { fg = "magenta" }
"function" = { fg = "blue" }
"type" = { fg = "yellow" }
"operator" = { fg = "cyan" }
"punctuation" = { fg = "foreground" }
"label" = { fg = "accent" }
"namespace" = { fg = "yellow" }

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "cyan", style = "curl" } }
"error" = { fg = "red" }
"warning" = { fg = "yellow" }
"info" = { fg = "blue" }
"hint" = { fg = "cyan" }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "yellow" }
"diff.minus" = { fg = "red" }

[palette]
background = "{{ background }}"
dark_background = "{{ dark_background }}"
lighter_background = "{{ lighter_background }}"
foreground = "{{ foreground }}"
bright_foreground = "{{ bright_foreground }}"
muted = "{{ muted }}"
selection = "{{ selection }}"
accent = "{{ accent }}"
red = "{{ red }}"
green = "{{ green }}"
yellow = "{{ yellow }}"
blue = "{{ blue }}"
magenta = "{{ magenta }}"
cyan = "{{ cyan }}"
orange = "{{ orange }}"
