-- Generated by riso. Edits are lost on the next theme change.
-- Require this module to colour a config from the active theme:
--   local theme = require("riso")
--   vim.api.nvim_set_hl(0, "Normal", { fg = theme.foreground, bg = theme.background })

return {
  mode = "{{ mode }}",

  background = "{{ background }}",
  dark_background = "{{ dark_background }}",
  lighter_background = "{{ lighter_background }}",

  foreground = "{{ foreground }}",
  dark_foreground = "{{ dark_foreground }}",
  bright_foreground = "{{ bright_foreground }}",

  accent = "{{ accent }}",
  muted = "{{ muted }}",
  selection = "{{ selection }}",

  red = "{{ red }}",
  green = "{{ green }}",
  yellow = "{{ yellow }}",
  blue = "{{ blue }}",
  magenta = "{{ magenta }}",
  cyan = "{{ cyan }}",
  orange = "{{ orange }}",

  bright_red = "{{ bright_red }}",
  bright_green = "{{ bright_green }}",
  bright_yellow = "{{ bright_yellow }}",
  bright_blue = "{{ bright_blue }}",
  bright_magenta = "{{ bright_magenta }}",
  bright_cyan = "{{ bright_cyan }}",

  font = {
    mono = "{{ font_mono }}",
    ui = "{{ font_ui }}",
    size = {{ font_size }},
  },
}
