/* Generated by riso. Edits are lost on the next theme change. */
.theme-{{ mode }} {
  --background-primary: {{ background }};
  --background-primary-alt: {{ dark_background }};
  --background-secondary: {{ dark_background }};
  --background-secondary-alt: {{ darker_background }};
  --background-modifier-border: {{ muted }};
  --background-modifier-form-field: {{ lighter_background }};
  --background-modifier-hover: {{ lighter_background }};

  --text-normal: {{ foreground }};
  --text-muted: {{ muted }};
  --text-faint: {{ dark_foreground }};
  --text-accent: {{ accent }};
  --text-accent-hover: {{ bright_foreground }};
  --text-on-accent: {{ background }};
  --text-selection: {{ selection }};
  --text-highlight-bg: {{ selection_background }};

  --text-error: {{ red }};
  --text-success: {{ green }};
  --text-warning: {{ yellow }};

  --interactive-normal: {{ lighter_background }};
  --interactive-hover: {{ selection }};
  --interactive-accent: {{ accent }};
  --interactive-accent-hover: {{ bright_foreground }};

  --titlebar-background: {{ dark_background }};
  --titlebar-text-color: {{ foreground }};
  --divider-color: {{ muted }};
  --scrollbar-thumb-bg: {{ muted }};

  --h1-color: {{ accent }};
  --h2-color: {{ accent }};
  --h3-color: {{ foreground }};

  --code-background: {{ dark_background }};
  --code-normal: {{ foreground }};
  --code-string: {{ green }};
  --code-keyword: {{ magenta }};
  --code-function: {{ blue }};
  --code-comment: {{ muted }};

  --font-text: "{{ font_ui }}";
  --font-monospace: "{{ font_mono }}";
}
