{
  "$schema": "vscode://schemas/color-theme",
  "name": "riso",
  "type": "{{ mode }}",
  "colors": {
    "editor.background": "{{ background }}",
    "editor.foreground": "{{ foreground }}",
    "editorCursor.foreground": "{{ bright_foreground }}",
    "editor.selectionBackground": "{{ selection_background }}",
    "editor.lineHighlightBackground": "{{ lighter_background }}",
    "editorLineNumber.foreground": "{{ muted }}",
    "editorLineNumber.activeForeground": "{{ foreground }}",
    "editorIndentGuide.background1": "{{ lighter_background }}",
    "editorWhitespace.foreground": "{{ muted }}",

    "activityBar.background": "{{ dark_background }}",
    "activityBar.foreground": "{{ foreground }}",
    "activityBarBadge.background": "{{ accent }}",
    "activityBarBadge.foreground": "{{ background }}",

    "sideBar.background": "{{ dark_background }}",
    "sideBar.foreground": "{{ foreground }}",
    "sideBarSectionHeader.background": "{{ lighter_background }}",

    "statusBar.background": "{{ dark_background }}",
    "statusBar.foreground": "{{ foreground }}",
    "statusBar.noFolderBackground": "{{ dark_background }}",
    "statusBar.debuggingBackground": "{{ accent }}",

    "titleBar.activeBackground": "{{ dark_background }}",
    "titleBar.activeForeground": "{{ foreground }}",
    "titleBar.inactiveBackground": "{{ darker_background }}",
    "titleBar.inactiveForeground": "{{ muted }}",

    "tab.activeBackground": "{{ background }}",
    "tab.activeForeground": "{{ bright_foreground }}",
    "tab.inactiveBackground": "{{ dark_background }}",
    "tab.inactiveForeground": "{{ muted }}",
    "tab.activeBorderTop": "{{ accent }}",

    "panel.background": "{{ dark_background }}",
    "panel.border": "{{ muted }}",
    "terminal.background": "{{ background }}",
    "terminal.foreground": "{{ foreground }}",
    "terminal.ansiBlack": "{{ color0 }}",
    "terminal.ansiRed": "{{ color1 }}",
    "terminal.ansiGreen": "{{ color2 }}",
    "terminal.ansiYellow": "{{ color3 }}",
    "terminal.ansiBlue": "{{ color4 }}",
    "terminal.ansiMagenta": "{{ color5 }}",
    "terminal.ansiCyan": "{{ color6 }}",
    "terminal.ansiWhite": "{{ color7 }}",
    "terminal.ansiBrightBlack": "{{ color8 }}",
    "terminal.ansiBrightRed": "{{ color9 }}",
    "terminal.ansiBrightGreen": "{{ color10 }}",
    "terminal.ansiBrightYellow": "{{ color11 }}",
    "terminal.ansiBrightBlue": "{{ color12 }}",
    "terminal.ansiBrightMagenta": "{{ color13 }}",
    "terminal.ansiBrightCyan": "{{ color14 }}",
    "terminal.ansiBrightWhite": "{{ color15 }}",

    "list.activeSelectionBackground": "{{ selection_background }}",
    "list.activeSelectionForeground": "{{ selection_foreground }}",
    "list.hoverBackground": "{{ lighter_background }}",

    "button.background": "{{ accent }}",
    "button.foreground": "{{ background }}",
    "focusBorder": "{{ accent }}",
    "input.background": "{{ lighter_background }}",
    "input.foreground": "{{ foreground }}",

    "errorForeground": "{{ red }}",
    "editorError.foreground": "{{ red }}",
    "editorWarning.foreground": "{{ yellow }}",
    "editorInfo.foreground": "{{ blue }}",

    "gitDecoration.addedResourceForeground": "{{ green }}",
    "gitDecoration.modifiedResourceForeground": "{{ yellow }}",
    "gitDecoration.deletedResourceForeground": "{{ red }}",
    "gitDecoration.untrackedResourceForeground": "{{ cyan }}"
  },
  "tokenColors": [
    { "scope": ["comment"], "settings": { "foreground": "{{ muted }}", "fontStyle": "italic" } },
    { "scope": ["string"], "settings": { "foreground": "{{ green }}" } },
    { "scope": ["constant.numeric"], "settings": { "foreground": "{{ orange }}" } },
    { "scope": ["constant.language"], "settings": { "foreground": "{{ orange }}" } },
    { "scope": ["keyword", "storage"], "settings": { "foreground": "{{ magenta }}" } },
    { "scope": ["entity.name.function", "support.function"], "settings": { "foreground": "{{ blue }}" } },
    { "scope": ["entity.name.type", "support.type"], "settings": { "foreground": "{{ yellow }}" } },
    { "scope": ["variable"], "settings": { "foreground": "{{ foreground }}" } },
    { "scope": ["variable.parameter"], "settings": { "foreground": "{{ orange }}" } },
    { "scope": ["keyword.operator"], "settings": { "foreground": "{{ cyan }}" } },
    { "scope": ["entity.name.tag"], "settings": { "foreground": "{{ red }}" } },
    { "scope": ["entity.other.attribute-name"], "settings": { "foreground": "{{ accent }}" } },
    { "scope": ["invalid"], "settings": { "foreground": "{{ bright_red }}" } }
  ]
}
