#!/usr/bin/env bash
#
# Rebuild the conformance fixtures from a checkout of upstream Omarchy.
#
# Usage: scripts/update-fixtures.sh [ref]
#
# The fixtures are the expected output of the upstream shell pipeline, so they
# must be regenerated whenever riso targets a new Omarchy release. Review the
# resulting diff: a change here is a change in what riso promises to match.

set -euo pipefail

REF="${1:-v4.0.0}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OMARCHY="$ROOT/target/omarchy-$REF"
FIXTURES="$ROOT/crates/riso-core/tests/fixtures"
WORK="$ROOT/target/fixtures-$REF"

# Templates kept as fixtures, chosen to exercise every dialect feature:
# plain keys, _strip, _rgb, mix, and the gradient helpers.
TEMPLATES=(ghostty.conf foot.ini hyprland.lua chromium.theme claude.json shell.toml)
# Themes whose full render is stored; two dark and one light.
RENDERED=(tokyo-night rose-pine catppuccin-latte)

if [[ ! -d $OMARCHY ]]; then
  git clone --depth 1 --branch "$REF" --quiet \
    https://github.com/basecamp/omarchy.git "$OMARCHY"
fi

PATCHED="$WORK/bin"
rm -rf "$WORK"
mkdir -p "$PATCHED"
for script in omarchy-theme-color omarchy-theme-set-templates; do
  sed '1s|^#!/bin/bash|#!/usr/bin/env bash|' "$OMARCHY/bin/$script" >"$PATCHED/$script"
  chmod +x "$PATCHED/$script"
done

rm -rf "$FIXTURES/themes" "$FIXTURES/palette" "$FIXTURES/templates" "$FIXTURES/rendered"
mkdir -p "$FIXTURES/themes" "$FIXTURES/palette" "$FIXTURES/templates" "$FIXTURES/rendered"

for theme_dir in "$OMARCHY"/themes/*/; do
  theme="$(basename "$theme_dir")"
  [[ -f "$theme_dir/colors.toml" ]] || continue
  cp "$theme_dir/colors.toml" "$FIXTURES/themes/$theme.toml"
  env PATH="$PATCHED:$PATH" bash "$PATCHED/omarchy-theme-color" \
    --file "$theme_dir/colors.toml" --all >"$FIXTURES/palette/$theme.tsv" 2>/dev/null
done

for template in "${TEMPLATES[@]}"; do
  cp "$OMARCHY/default/themed/$template.tpl" "$FIXTURES/templates/"
done

for theme in "${RENDERED[@]}"; do
  home="$WORK/$theme"
  staged="$home/.local/state/omarchy/current/next-theme"
  mkdir -p "$staged" "$home/.config/omarchy/themed"
  cp "$OMARCHY/themes/$theme/colors.toml" "$staged/colors.toml"
  env HOME="$home" OMARCHY_PATH="$OMARCHY" PATH="$PATCHED:$PATH" \
    bash "$PATCHED/omarchy-theme-set-templates" 2>/dev/null
  mkdir -p "$FIXTURES/rendered/$theme"
  for template in "${TEMPLATES[@]}"; do
    cp "$staged/$template" "$FIXTURES/rendered/$theme/$template"
  done
done

cat >"$FIXTURES/README.md" <<EOF
# Conformance fixtures

Generated by \`scripts/update-fixtures.sh\` from Omarchy $REF.

- \`themes/\` - each theme's \`colors.toml\`, verbatim
- \`palette/\` - what \`omarchy-theme-color --all\` resolves that file to
- \`templates/\` - templates chosen to exercise every dialect feature
- \`rendered/\` - what \`omarchy-theme-set-templates\` renders them to

These files are copied from [Omarchy](https://github.com/basecamp/omarchy),
which is MIT licensed, and are used here to verify interoperability.
Do not edit them by hand: regenerate them instead.
EOF

echo "fixtures rebuilt from omarchy $REF"
